name: zint-snap # you probably want to 'snapcraft register <name>'
version: '2.11.1.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: A barcode encoding tool supporting over 50 symbologies. # 79 char long summary
description: |
  Encodes data into any of the following: Australia Post barcode, Aztec Code, 
  Aztec Runes, Channel Code, Codabar, Codablock-F, Code 11, Code 128, Code 16K, 
  Code 2 of 5 (Including IATA, Datalogic, ITF14, Deutsche Post Leitcode and Identcode), 
  Code 32 (Italian Pharmacode), Code 39, Code 39+, Code 49, Code 93, Code One, 
  Data Matrix (including DMRE), DotCode, Dutch Post KIX, EAN, Grid Matrix, 
  GS-1 DataBar (including stacked and composite symbols), Han Xin, HIBC, 
  Japan Post, Korea Post, LOGMARS, MaxiCode, MSI, PDF417 and Micro PDF417, 
  Pharmacode, POSTNET, PLANET, QR Code and Micro QR, Royal Mail 4-state (RM4SCC) 
  and Mailmark, Telepen, Ultracode, UPC-A, UPC-E, UPNQR and USPS Intelligent Mail.

  Automated ECI switching to support all Unicode characters and automated 
  FNC1 character insertion in GS1 mode. Save to PNG, BMP, TIF, GIF, PCX, 
  SVG, WMF and EPS. Includes CLI, GUI and API for calling from other applications.

  _More build details: https://github.com/Joker2770/zint-snap.git_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
license: 'GPL-3.0+'
architectures:
  - build-on: amd64

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/local/share:
    bind: $SNAP/usr/local/share
  /usr/share/X11:
    bind: $SNAP/usr/share/X11

apps:
  zint-snap:
    command: usr/local/bin/launcher.sh
    extensions: [kde-neon]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - gsettings
    environment:
      DISABLE_WAYLAND: 1
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
  cli:
    command: usr/local/bin/zint
    plugs:
      - home
      - removable-media

parts:
  zint-snap:
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
    source: https://git.code.sf.net/p/zint/code
    source-type: git
    source-branch: master
    source-depth: 1
    build-snaps:
      - kde-frameworks-5-core18-sdk
    build-packages:
      - gcc
      - make
      - zlib1g-dev
      - libpng-dev
      - qtbase5-dev
      - qtbase5-private-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5svg5-dev
  
    stage-packages:
      - zlib1g
      - libpng16-16
      - libqt5concurrent5
      - libqt5dbus5
      - libqt5x11extras5

  include-launcher:
    plugin: dump
    source: "https://github.com/Joker2770/zint-snap.git"
    source-depth: 1
    source-branch: main
    source-type: git
    organize:
      "launcher.sh" : usr/local/bin/
    prime:
      - -README*
      - -LICENSE
      - -snap
      - -bak
    override-build: |
      snapcraftctl build
      chmod +x launcher.sh

